from constants import *

ANIME_LIST = 'AnimeList'
ANIME_LIST_POPULAR = ANIME_LIST + '/MostPopular'
ANIME_LIST_LATEST = ANIME_LIST + '/LatestUpdate'
ANIME_LIST_NEWEST = ANIME_LIST + '/Newest'
ANIME_LIST_ONGOING = ANIME_LIST + '/Status/Ongoing'

ANIME_SEARCH_ENDPOINT = 'Search/Anime'

UPCOMING_ANIME = 'UpcomingAnime'

ANIME_LIST_FILTER_MAP = {
    SORT_ALPHABETICALLY_ACTION: ANIME_LIST,
    SORT_BY_POPULAR_ACTION: ANIME_LIST_POPULAR,
    LATEST_UPDATE_ACTION: ANIME_LIST_LATEST,
    NEW_ANIME_ACTION: ANIME_LIST_NEWEST
}
